name: Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Change directory
      run: cd path/to/your/project

    - name: Install dependencies
      run: npm install
